apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ca-mario
  namespace: kube-system
spec:
  addresses:
    - 172.25.10.200-172.25.10.201
  autoAssign: true
  avoidBuggyIPs: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ca-mario
  namespace: kube-system
spec:
  ipAddressPools:
    - ca-mario
