apiVersion: v1
kind: Service
metadata:
  name: mario-clone-service
  namespace: mario-game
spec:
  type: LoadBalancer
  loadBalancerIP: "172.25.10.200"
  selector:
    app: mario-clone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


