apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mario-game

resources:
  - namespace.yaml
  - config.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - argocd-server-lb.yaml  # ‚Üê ADD THIS LINE

images:
  - name: mario-clone
    newName: acxcontregwus2-c6chcgfjardafsb5.azurecr.io/mario-clone
    newTag: v2














