apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: mario-pool
  namespace: kube-system
spec:
  addresses:
  - 172.25.10.200/32
  - 172.25.10.201/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: mario-l2
  namespace: kube-system
spec:
  ipAddressPools:
  - mario-pool

